[project]
name = "calcreport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    'sympy',
    'pint',
    'pandas',
    'numpy',
    'IPython',
    'cmarkgfm'
]

[project.scripts]
notebooktohtml = "calcreport.export.notebooktohtml:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

